package DAO;
// Generated 26/04/2016 03:15:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Accesorio generated by hbm2java
 */
public class Accesorio  implements java.io.Serializable {


     private Integer idaccesorio;
     private Articulo articulo;
     private String tipo;
     private String nombre;
     private String marca;

    public Accesorio() {
    }

	
    public Accesorio(Integer idaccesorio, Articulo articulo, String tipo) {
        this.idaccesorio = idaccesorio;
        this.articulo = articulo;
        this.tipo = tipo;
    }
    public Accesorio(Integer idaccesorio, Articulo articulo, String tipo, String nombre, String marca) {
       this.idaccesorio = idaccesorio;
       this.articulo = articulo;
       this.tipo = tipo;
       this.nombre = nombre;
       this.marca = marca;
    }
   
    public Integer getIdaccesorio() {
        return this.idaccesorio;
    }
    
    public void setIdaccesorio(Integer idaccesorio) {
        this.idaccesorio = idaccesorio;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }




}


