package DAO;
// Generated 13/04/2016 04:25:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private BigDecimal idarticulo;
     private Articulo articulo;
     private String estado;

    public Estado() {
    }

	
    public Estado(Articulo articulo) {
        this.articulo = articulo;
    }
    public Estado(Articulo articulo, String estado) {
       this.articulo = articulo;
       this.estado = estado;
    }
   
    public BigDecimal getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(BigDecimal idarticulo) {
        this.idarticulo = idarticulo;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


