package DAO;
// Generated 13/04/2016 04:25:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Instrumento generated by hbm2java
 */
public class Instrumento  implements java.io.Serializable {


     private BigDecimal idinstrumento;
     private Articulo articulo;
     private Date ano;
     private String marca;
     private String tipo;
     private String nombreinstrumento;

    public Instrumento() {
    }

	
    public Instrumento(BigDecimal idinstrumento, Articulo articulo, String tipo) {
        this.idinstrumento = idinstrumento;
        this.articulo = articulo;
        this.tipo = tipo;
    }
    public Instrumento(BigDecimal idinstrumento, Articulo articulo, Date ano, String marca, String tipo, String nombreinstrumento) {
       this.idinstrumento = idinstrumento;
       this.articulo = articulo;
       this.ano = ano;
       this.marca = marca;
       this.tipo = tipo;
       this.nombreinstrumento = nombreinstrumento;
    }
   
    public BigDecimal getIdinstrumento() {
        return this.idinstrumento;
    }
    
    public void setIdinstrumento(BigDecimal idinstrumento) {
        this.idinstrumento = idinstrumento;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getNombreinstrumento() {
        return this.nombreinstrumento;
    }
    
    public void setNombreinstrumento(String nombreinstrumento) {
        this.nombreinstrumento = nombreinstrumento;
    }




}


