package DAO;
// Generated 13/04/2016 04:25:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private BigDecimal idlibro;
     private Articulo articulo;
     private String editorial;
     private String nombreautor;
     private String nombre;
     private String genero;
     private Date ano;

    public Libro() {
    }

	
    public Libro(BigDecimal idlibro, Articulo articulo) {
        this.idlibro = idlibro;
        this.articulo = articulo;
    }
    public Libro(BigDecimal idlibro, Articulo articulo, String editorial, String nombreautor, String nombre, String genero, Date ano) {
       this.idlibro = idlibro;
       this.articulo = articulo;
       this.editorial = editorial;
       this.nombreautor = nombreautor;
       this.nombre = nombre;
       this.genero = genero;
       this.ano = ano;
    }
   
    public BigDecimal getIdlibro() {
        return this.idlibro;
    }
    
    public void setIdlibro(BigDecimal idlibro) {
        this.idlibro = idlibro;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getEditorial() {
        return this.editorial;
    }
    
    public void setEditorial(String editorial) {
        this.editorial = editorial;
    }
    public String getNombreautor() {
        return this.nombreautor;
    }
    
    public void setNombreautor(String nombreautor) {
        this.nombreautor = nombreautor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Date getAno() {
        return this.ano;
    }
    
    public void setAno(Date ano) {
        this.ano = ano;
    }




}


