package DAO;
// Generated 26/04/2016 03:15:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Musica generated by hbm2java
 */
public class Musica  implements java.io.Serializable {


     private Integer idmusica;
     private Articulo articulo;
     private String autor;
     private String genero;
     private int ano;
     private String formato;

    public Musica() {
    }

	
    public Musica(Integer idmusica, Articulo articulo, String formato) {
        this.idmusica = idmusica;
        this.articulo = articulo;
        this.formato = formato;
    }
    public Musica(Integer idmusica, Articulo articulo, String autor, String genero, Integer ano, String formato) {
       this.idmusica = idmusica;
       this.articulo = articulo;
       this.autor = autor;
       this.genero = genero;
       this.ano = ano;
       this.formato = formato;
    }
   
    public Integer getIdmusica() {
        return this.idmusica;
    }
    
    public void setIdmusica(Integer idmusica) {
        this.idmusica = idmusica;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }




}


