package DAO;
// Generated 13/04/2016 04:25:11 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Prestigioconsumidor generated by hbm2java
 */
public class Prestigioconsumidor  implements java.io.Serializable {


     private String correo;
     private Usuario usuario;
     private BigDecimal prestigio;

    public Prestigioconsumidor() {
    }

    public Prestigioconsumidor(Usuario usuario, BigDecimal prestigio) {
       this.usuario = usuario;
       this.prestigio = prestigio;
    }
   
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getPrestigio() {
        return this.prestigio;
    }
    
    public void setPrestigio(BigDecimal prestigio) {
        this.prestigio = prestigio;
    }




}


