package DAO;
// Generated 26/04/2016 03:15:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Sonido generated by hbm2java
 */
public class Sonido  implements java.io.Serializable {


     private Integer idsonido;
     private Articulo articulo;
     private String nombre;
     private String tipo;
     private Double potencia;
     private String marca;

    public Sonido() {
    }

	
    public Sonido(Integer idsonido, Articulo articulo, String tipo) {
        this.idsonido = idsonido;
        this.articulo = articulo;
        this.tipo = tipo;
    }
    public Sonido(Integer idsonido, Articulo articulo, String nombre, String tipo, Double potencia, String marca) {
       this.idsonido = idsonido;
       this.articulo = articulo;
       this.nombre = nombre;
       this.tipo = tipo;
       this.potencia = potencia;
       this.marca = marca;
    }
   
    public Integer getIdsonido() {
        return this.idsonido;
    }
    
    public void setIdsonido(Integer idsonido) {
        this.idsonido = idsonido;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Double getPotencia() {
        return this.potencia;
    }
    
    public void setPotencia(Double potencia) {
        this.potencia = potencia;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }




}


